### ISSUE TITLE
Allow download of rust.json via API call

### ISSUE THREAD

**Issue by wischi-chr** [Skippeh/calcrust.com-backend#4]
The calcrust API is backed (if I understand the source correctly) by `data/rust.json`. The API call `/dump` allows to get most information in bulk, but sadly not everything (for example DamageInfo is missing)

It would be great if the entire `rust.json` would be accessible via an API call (e.g. `/fulldump` -> should directly reflect rust.json)

thanks.

**Comment by Skippeh** [comment]
I'll add this ASAP.

**Comment by Skippeh** [comment]
I've added an api path called /dump/full. It returns everything. I hope it will suffice for you. :)

**Comment by wischi-chr** [comment]
Thanks that's great.
